### ISSUE TITLE
Shadow appears on using in react project

### ISSUE THREAD

**Issue by Spyware007** [ashutosh1919/react-awesome-shapes#44]
A blackish shadow is appearing in my react project while using this on my website

<img width="234" alt="Screenshot 2022-03-02 at 3 12 34 PM" src="https://user-images.githubusercontent.com/89961974/156336308-7cc4b036-db6f-4e61-a218-7bb31bb78730.png">
!

Please check this!

**Comment by ashutosh1919** [comment]
@Spyware007 I think that is not shadow and we need to change the background color of the component. Will change in future build. Let it stay open till then.

**Comment by Spyware007** [comment]
okay @ashutosh1919  I m opening one more issue in a few mins please check that once!

**Comment by Spyware007** [comment]
I tried background color transparent but it's not working ??
Can you provide any temporary fix?? Please! @ashutosh1919

**Comment by ashutosh1919** [comment]
@Spyware007 it should be similar fix but I have to check.

**Comment by Sachin-chaurasiya** [comment]
@Spyware007 , is this fixed or you are still facing some issues?

**Comment by Spyware007** [comment]
There was something like box-shadow but now it's fixed! @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
@Spyware007 Closing this issue and thanks for verifying,
