### ISSUE TITLE
diamond to square 

### ISSUE THREAD

**Issue by Spyware007** [ashutosh1919/react-awesome-shapes#45]
I am trying to use the diamond shape but it's converted into a square. Actually, I am using className prop on the component for adding some cool animations.
It stays for some time as a diamond and then it jumps back to square as shown in the image below!
<img width="663" alt="Screenshot 2022-03-02 at 7 58 53 PM" src="https://user-images.githubusercontent.com/89961974/156381553-a204d289-244b-4c50-b3f3-aede35cc2da5.png">

<img width="199" alt="Screenshot 2022-03-02 at 7 58 26 PM" src="https://user-images.githubusercontent.com/89961974/156381210-b5f1640e-a165-46fd-9233-7cbfb8a90f70.png">
<img width="185" alt="Screenshot 2022-03-02 at 7 58 21 PM" src="https://user-images.githubusercontent.com/89961974/156381221-faf56ece-216f-4483-b4e4-483cb252a156.png">

**Comment by ashutosh1919** [comment]
@Spyware007 yes i noticed this issue and it is there when you try to animate shape in any way. The reason may be because `clip-path` is not reliable to start with. The fix may be that we need to programmatically rotate the shape.

**Comment by Spyware007** [comment]
you mean transform: rotate("x deg")??
I tried this but after close inspection, it rotates the background, not the clip-path!

**Comment by ashutosh1919** [comment]
No, I mean you need to do it using JS.

**Comment by Sachin-chaurasiya** [comment]
@Spyware007 , is this still an issue.

**Comment by Spyware007** [comment]
@Sachin-chaurasiya  yes it is still an issue!
To be clearer it happens when I added className for animating the shape using keyframes!

**Comment by Sachin-chaurasiya** [comment]
@Spyware007 , if possible can you provide codepan or sandbox link , it would be easy to debug.

**Comment by Spyware007** [comment]
https://codesandbox.io/s/dreamy-sutherland-5y3vr6?file=/src/App.js
Here you go!

**Comment by ShaileshParmar11** [comment]
@Spyware007 @Sachin-chaurasiya , After taking deep dive in the code i come to know that the CSS wrote to rotate Square shaped in to Diamond is clashing with the class provided for animation.
Css to convert Square to diamond:-
`transform: rotate(45deg);`

Animation css modifies the transform property, due to that shape converts it self in to square which is base shape.
animation key frame:-

```
@keyframes float {
  0% {
    transform: translatey(0px);
  }
  50% {
    transform: translatey(-20px);
  }
  100% {
    transform: translatey(0px);
  }
}
```

ill try to research on this part and ill let you know if found any solution.

**Comment by Sachin-chaurasiya** [comment]
> @Spyware007 @Sachin-chaurasiya , After taking deep dive in the code i come to know that the CSS wrote to rotate Square shaped in to Diamond is clashing with the class provided for animation.
> Css to convert Square to diamond:-
> `transform: rotate(45deg);`
> 
> Animation css modifies the transform property, due to that shape converts it self in to square which is base shape.
> animation key frame:-
> 
> ```
> @keyframes float {
>   0% {
>     transform: translatey(0px);
>   }
>   50% {
>     transform: translatey(-20px);
>   }
>   100% {
>     transform: translatey(0px);
>   }
> }
> ```
> 
> ill try to research on this part and ill let you know if found any solution.
> 

Thanks, @ShaileshParmar11 , welcome to the community.
