### ISSUE TITLE
Create seperate folder for constants

### ISSUE THREAD

**Issue by ashutosh1919** [ashutosh1919/react-awesome-shapes#49]
Creating a seperate folder called `shapes/data` which will contain all constants related files in that. For example `polygonPaths.tsx` used for `Polygon` should be in there. The PR for new `Star` shape is open and that also have `clip-path`. In future, we may get many such shape paths that we want to store and storing them in same dir is not good.

**Comment by Spyware007** [comment]
@ashutosh1919  Can I do this as I created that star shape?

**Comment by Sachin-chaurasiya** [comment]
Fixed with #51
