### ISSUE TITLE
Add pre-commit to format all JS files for indentation

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [ashutosh1919/react-awesome-shapes#5]

**Comment by Sachin-chaurasiya** [comment]
@ashutosh1919 , please assign this to me.

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya Also note that once you raise PR for this, what I will do:
- I will manually run command to format all files.
- I will push it. You will need to sync your PR with new files. 

This will help in consistency for all future PRs.
