### ISSUE TITLE
Getting overflow scroll on some contents of the page

### ISSUE THREAD

**Issue by rocodes01** [ashutosh1919/react-awesome-shapes#50]
![image](https://user-images.githubusercontent.com/66406171/156857548-290a9ad0-100c-4db1-bc9b-e1eef115e196.png)
![image](https://user-images.githubusercontent.com/66406171/156857563-5bf87d8a-54cf-4403-874b-3a0080a12187.png)

Browser: Brave browser v1.136

**Comment by ashutosh1919** [comment]
Overflow scroll is expected. @Sachin-chaurasiya @mohittk
