### ISSUE TITLE
Remove Triangle, Square and Hexagon

### ISSUE THREAD

**Issue by ashutosh1919** [ashutosh1919/react-awesome-shapes#60]
Since we now have `Polygon` as generalized shape, we can remove `Triangle`, `Square` and `Hexagon` since they are not adding much to the project.

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya , should I assign this issue to you?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya , should I assign this issue to you?
> 

@ashutosh1919 , sure.

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya Please Remove the shapes from UI as well. We don't want to reuse `Polygon` multiple times. It confuses users.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Please Remove the shapes from UI as well. We don't want to reuse `Polygon` multiple times. It confuses users.

@ashutosh1919 , Sure.
