### ISSUE TITLE
Add different varieties of shapes

### ISSUE THREAD

**Issue by mohittk** [ashutosh1919/react-awesome-shapes#8]

**Comment by mohittk** [comment]
#7

**Comment by mohittk** [comment]
Need to add more shapes

**Comment by ashutosh1919** [comment]
closing this as of now because we should now focus on completing the website first. Then we will come back to build more shapes.

**Comment by mohittk** [comment]
> closing this as of now because we should now focus on completing the website first. Then we will come back to build more shapes.

Yes! roger that.
